from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager

def instrument_imports() -> AbstractContextManager[None]: ...
def Setup(argv: list[str], test_one_input: Callable[[bytes], object]) -> None: ...
def Fuzz() -> None: ...
