name: ClusterFuzzLite batch fuzzing

on:
  workflow_dispatch:
  schedule:
    - cron: "41 3 * * 2"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BatchFuzzing:
    runs-on: [self-hosted, Linux, X64]
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: batch
          output-sarif: true
          sanitizer: ${{ matrix.sanitizer }}
