name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * 3"

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: scorecard
    runs-on: [self-hosted, Linux, X64]
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2 # v2.4.3
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: scorecard.sarif
