name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  zizmor:
    name: zizmor
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          clean: false
          persist-credentials: false
      - name: Prepare self-hosted workspace
        uses: ./.github/actions/prepare-workspace
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Run zizmor
        continue-on-error: true
        run: |
          uvx zizmor --format sarif .github/workflows/ > zizmor.sarif
      - uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        if: always()
        with:
          sarif_file: zizmor.sarif
